import {useEffect,useMemo,useState} from 'react';
import QRCode from 'qrcode';
import {apiGet,apiPost,apiPut,CircleRow} from './lib/api';
import {riyadhDate} from './lib/date';
import EvaluationCriteriaPanel from './EvaluationCriteriaPanel';

const ORIGIN='https://ashour-bukhari-cleana.vercel.app';
const points=(v:any)=>{const n=Number(v||0);return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')};

export default function CircleSettings({circles}:{currentRole:string;circles:CircleRow[]}){
 const active=circles.filter(c=>c.is_active!==false),[circleId,setCircleId]=useState(active[0]?.id||''),[data,setData]=useState<any>(null),[motivation,setMotivation]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[qr,setQr]=useState(''),[taskEdit,setTaskEdit]=useState<any>(null),[rewardEdit,setRewardEdit]=useState<any>(null);
 const month=riyadhDate().slice(0,7);
 useEffect(()=>{if(!circleId&&active.length)setCircleId(active[0].id)},[active.length,circleId]);
 async function load(id=circleId){if(!id)return;setBusy(true);setMessage('');try{
  const [settings,m]=await Promise.all([apiGet<any>(`/api/ops?action=circle-settings&circle_id=${id}`),apiGet<any>(`/api/ops?action=motivation&sub=list&month=${month}&circle_id=${id}`)]);
  setData(settings);setMotivation(m);
 }catch(e){setMessage(e instanceof Error?e.message:'تعذر تحميل إعدادات الحلقة')}finally{setBusy(false)}}
 useEffect(()=>{if(circleId)void load(circleId)},[circleId]);
 const attendanceUrl=useMemo(()=>data?.circle?.attendance_token?`${ORIGIN}/?attendance=${data.circle.attendance_token}`:'',[data?.circle?.attendance_token]);
 useEffect(()=>{if(!attendanceUrl){setQr('');return}QRCode.toDataURL(attendanceUrl,{width:360,margin:2,errorCorrectionLevel:'M'}).then(setQr).catch(()=>setQr(''))},[attendanceUrl]);
 async function saveTiming(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.circle_id=circleId;if(b.start_mode==='asr')b.start_time='';delete b.start_mode;setBusy(true);setMessage('');try{await apiPut('/api/ops?action=circle-settings',b);setMessage('تم حفظ إعدادات حضور الحلقة.');await load()}catch(x){setMessage(x instanceof Error?x.message:'تعذر الحفظ')}finally{setBusy(false)}}
 async function regenerate(){if(!confirm('سيصبح الرمز المطبوع الحالي غير صالح. هل تريد إصدار QR ثابت جديد؟'))return;setBusy(true);try{await apiPost('/api/ops?action=circle-settings&sub=regenerate-qr',{circle_id:circleId});setMessage('تم إصدار رمز ثابت جديد للحلقة.');await load()}catch(x){setMessage(x instanceof Error?x.message:'تعذر إصدار الرمز')}finally{setBusy(false)}}
 function printQr(){if(!qr||!data?.circle)return;const w=window.open('','_blank','width=700,height=850');if(!w)return;w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>QR ${data.circle.name}</title><style>body{font-family:Arial;text-align:center;padding:45px;color:#153e34}img{width:360px;max-width:90%}h1{font-size:30px;margin:10px}p{font-size:18px;line-height:1.8}.box{border:3px solid #153e34;border-radius:28px;padding:30px}.small{font-size:13px;color:#667}</style></head><body><div class="box"><h1>حلقات عاشور بخاري</h1><h2>${data.circle.name}</h2><img src="${qr}"><p><b>امسح الرمز لتسجيل حضورك تلقائيًا</b><br>الرمز ثابت ومخصص لهذه الحلقة.</p><div class="small">لا يحتاج إلى تحديد الموقع الجغرافي.</div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
 async function taskSave(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.circle_id=circleId;setBusy(true);try{if(taskEdit){b.task_id=taskEdit.id;await apiPut('/api/ops?action=motivation&sub=task-edit',b)}else await apiPost('/api/ops?action=motivation&sub=task',b);setTaskEdit(null);e.currentTarget.reset();await load()}catch(x){setMessage(x instanceof Error?x.message:'تعذر حفظ المهمة')}finally{setBusy(false)}}
 async function rewardSave(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.circle_id=circleId;setBusy(true);try{if(rewardEdit){b.reward_id=rewardEdit.id;await apiPut('/api/ops?action=motivation&sub=reward-edit',b)}else await apiPost('/api/ops?action=motivation&sub=reward',b);setRewardEdit(null);e.currentTarget.reset();await load()}catch(x){setMessage(x instanceof Error?x.message:'تعذر حفظ الجائزة')}finally{setBusy(false)}}
 if(!active.length)return <div className="emptyState">لا توجد حلقة ضمن نطاق هذا الحساب.</div>;
 const c=data?.circle,tasks=(motivation?.tasks||[]).filter((x:any)=>x.is_active!==false),rewards=(motivation?.rewards||[]).filter((x:any)=>x.is_active!==false);
 return <div className="circleSettingsPage">
  <div className="circleSettingsSelector"><div><span className="panelEyebrow">إعدادات مستقلة لكل حلقة</span><h3>إعدادات الحلقة</h3><p>الحضور والتقييم والنقاط والجوائز مرتبطة بالحلقة نفسها، وتظهر لجميع معلميها.</p></div><label className="field"><span>الحلقة</span><select value={circleId} onChange={e=>setCircleId(e.target.value)}>{active.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></div>
  {message&&<div className="notice">{message}</div>}{busy&&!data&&<div className="emptyState">جارٍ تحميل الإعدادات...</div>}
  {c&&<><section className="circleSettingsSection"><div className="circleSettingsHead"><div><span>01</span><h3>الحضور ووقت الحلقة</h3><p>الافتراضي يبدأ مع أذان العصر في مكة. يمكن تخصيص وقت مختلف لهذه الحلقة فقط.</p></div><div className="timingBadge">{c.automatic_start?'أذان العصر':'وقت مخصص'}<b>{String(c.effective_start_time).slice(0,5)}</b></div></div>
   <form className="circleTimingForm" onSubmit={saveTiming}>
    <label className="field"><span>طريقة بدء الحلقة</span><select name="start_mode" defaultValue={c.automatic_start?'asr':'custom'} key={c.id+'mode'}><option value="asr">أذان العصر في مكة — افتراضي</option><option value="custom">وقت ثابت مخصص</option></select></label>
    <label className="field"><span>الوقت المخصص (يُترك فارغًا مع الأذان)</span><input name="start_time" type="time" defaultValue={c.start_time?String(c.start_time).slice(0,5):''} key={c.id+'time'}/></label>
    <label className="field"><span>يبدأ وصف «متأخر» بعد</span><div className="numberSuffix"><input name="late_after_minutes" type="number" min="1" max="240" defaultValue={c.late_after_minutes||70}/><b>دقيقة</b></div></label>
    <label className="field"><span>يبدأ الخصم بعد</span><div className="numberSuffix"><input name="deduction_after_minutes" type="number" min="1" max="300" defaultValue={c.deduction_after_minutes||90}/><b>دقيقة</b></div></label>
    <label className="field"><span>يبدأ الخصم الثاني بعد</span><div className="numberSuffix"><input name="major_deduction_after_minutes" type="number" min="1" max="360" defaultValue={c.major_deduction_after_minutes||120}/><b>دقيقة</b></div></label>
    <button className="primary" disabled={busy}>حفظ إعدادات الحضور</button>
   </form>
   <div className="attendanceRuleStrip"><article><b>30/30</b><span>حتى بدء الخصم</span></article><article><b>20/30</b><span>بعد الخصم الأول</span></article><article><b>10/30</b><span>بعد الخصم الثاني</span></article><article><b>0/30</b><span>غياب</span></article><article><b>مستبعد</b><span>مستأذن</span></article></div>
  </section>
  <section className="circleSettingsSection qrSettingsSection"><div className="circleSettingsHead"><div><span>02</span><h3>QR الحضور الثابت</h3><p>رمز واحد ثابت لهذه الحلقة؛ يطبع ويعلق في مقر التحفيظ، ولا يستخدم GPS.</p></div><b className="fixedQrBadge">ثابت</b></div><div className="qrSettingsGrid"><div className="qrPrintCard">{qr?<img src={qr} alt={'QR حضور '+c.name}/>:<div className="qrLoading">جارٍ إنشاء QR...</div>}<b>{c.name}</b><small>المسح يسجل حضور الطالب مباشرة إذا كان من طلاب الحلقة.</small></div><div className="qrActions"><button className="primary" type="button" onClick={printQr} disabled={!qr}>طباعة بطاقة QR</button><button className="secondary" type="button" onClick={regenerate}>إصدار رمز جديد</button><p>إصدار رمز جديد يستخدم فقط عند الحاجة؛ الرمز الحالي يبقى ثابتًا ما لم تضغط هذا الزر.</p></div></div></section>
  <section className="circleSettingsSection"><div className="circleSettingsHead"><div><span>03</span><h3>معايير السجل والتقييم</h3><p>الأوزان مجموعها 100%. التعديل يحفظ للشهر القادم حتى لا تتغير نتائج الشهر الجاري.</p></div></div><EvaluationCriteriaPanel circles={active} month={month} selectedCircleId={circleId} hideSelector/></section>
  <section className="circleSettingsSection"><div className="circleSettingsHead"><div><span>04</span><h3>النقاط والمهام</h3><p>لكل حلقة مهامها وقيمة نقاطها الخاصة.</p></div></div>
   <form className="quickForm taskConfigForm" key={taskEdit?.id||'new-task'} onSubmit={taskSave}><label className="field"><span>اسم المهمة</span><input name="name" defaultValue={taskEdit?.name||''} required/></label><label className="field"><span>نوع الإجابة</span><select name="answer_type" defaultValue={taskEdit?.answer_type||'done'}><option value="done">تم / لم يتم</option><option value="count">عدد</option></select></label><label className="field"><span>الحد الأعلى</span><input name="max_units" type="number" min="1" max="100" defaultValue={taskEdit?.max_units||1}/></label><label className="field"><span>أقصى نقاط</span><input name="max_points" type="number" min="0.01" step="0.01" defaultValue={taskEdit?.max_points||1} required/></label><label className="field"><span>الترتيب</span><input name="sort_order" type="number" min="0" defaultValue={taskEdit?.sort_order||0}/></label><button className="primary">{taskEdit?'حفظ التعديل':'إضافة مهمة'}</button>{taskEdit&&<button type="button" className="secondary" onClick={()=>setTaskEdit(null)}>إلغاء</button>}</form>
   <div className="settingsItemsGrid">{tasks.map((t:any)=><article key={t.id}><div><b>{t.name}</b><small>{t.answer_type==='done'?'تم/لم يتم':'حتى '+t.max_units} • {points(t.max_points)} نقطة</small></div><div><button className="secondary" onClick={()=>setTaskEdit(t)}>تعديل</button><button className="dangerText" onClick={async()=>{if(confirm('إيقاف هذه المهمة؟')){await apiPost('/api/ops?action=motivation&sub=task-delete',{task_id:t.id});await load()}}}>إيقاف</button></div></article>)}</div>
  </section>
  <section className="circleSettingsSection"><div className="circleSettingsHead"><div><span>05</span><h3>الجوائز</h3><p>رصيد الجوائز وتكلفتها بالنقاط مستقلان لكل حلقة.</p></div></div>
   <form className="quickForm" key={rewardEdit?.id||'new-reward'} onSubmit={rewardSave}><label className="field"><span>اسم الجائزة</span><input name="name" defaultValue={rewardEdit?.name||''} required/></label><label className="field"><span>تكلفة النقاط</span><input name="points_cost" type="number" min="1" defaultValue={rewardEdit?.points_cost||1} required/></label><label className="field"><span>الكمية</span><input name="stock" type="number" min="0" defaultValue={rewardEdit?.stock||0} required/></label><label className="field"><span>رابط الصورة</span><input name="image_path" defaultValue={rewardEdit?.image_path||''}/></label><label className="field"><span>الوصف</span><input name="description" defaultValue={rewardEdit?.description||''}/></label><button className="primary">{rewardEdit?'حفظ التعديل':'إضافة جائزة'}</button>{rewardEdit&&<button type="button" className="secondary" onClick={()=>setRewardEdit(null)}>إلغاء</button>}</form>
   <div className="settingsItemsGrid">{rewards.map((r:any)=><article key={r.id}><div><b>{r.name}</b><small>{r.points_cost} نقطة • المتاح {r.stock}</small></div><div><button className="secondary" onClick={()=>setRewardEdit(r)}>تعديل</button><button className="dangerText" onClick={async()=>{if(confirm('إيقاف هذه الجائزة؟')){await apiPost('/api/ops?action=motivation&sub=reward-delete',{reward_id:r.id});await load()}}}>إيقاف</button></div></article>)}</div>
  </section></>}
 </div>
}
