import {useState} from 'react';
import {apiPost} from './lib/api';
import {MadinahMushafRange,madinahSurahName} from './MadinahMushafRange';
import {isNetworkFailure,pendingOfflineCount,queueOfflineOperation} from './lib/offline';

function quranText(item:any){if(!item)return 'لم يسجل';return madinahSurahName(Number(item.surah_no||1))+' ص'+(item.from_page||'—')+' ← '+madinahSurahName(Number(item.to_surah_no||item.surah_no||1))+' ص'+(item.to_page||'—')}
function resultFor(row:any,id:string){return (row?.criteria_results||[]).find((x:any)=>String(x.id)===String(id))}
function customCriteria(criteria:any[]){return (criteria||[]).filter((x:any)=>!x.system_key)}

export function TeacherFlexibleCriteria({data,date,onRefresh}:{data:any;date:string;onRefresh:()=>Promise<void>}){
 const [edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rows=data?.students||[];
 const criteriaMap=data?.criteria_by_circle||{};
 const hasCustom=Object.values(criteriaMap).some((list:any)=>customCriteria(list).length);
 if(!hasCustom)return null;
 async function save(e:any){e.preventDefault();if(!edit)return;setBusy(true);setError('');try{const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.student_id=edit.student.id;body.record_date=date;body.criterion_id=edit.criterion.id;if(edit.criterion.kind==='task')body.completed=body.completed==='on';await apiPost('/api/ops?action=criterion-record',body);setEdit(null);await onRefresh()}catch(x){setError(x instanceof Error?x.message:'تعذر حفظ المعيار')}finally{setBusy(false)}}
 return <section className="flexCriteriaToday"><div className="panelHead"><div><span className="panelEyebrow">المعايير الإضافية</span><h3>سجل معايير الحلقة — {date}</h3></div><small>الدرجة تحسب تلقائيًا من الإنجاز</small></div>{error&&<div className="notice">{error}</div>}<div className="flexCriteriaStudents">{rows.map((student:any)=>{const criteria=customCriteria(criteriaMap[student.circle_id]||[]);if(!criteria.length)return null;return <article key={student.id}><div className="flexStudentHead"><b>{student.full_name}</b><small>{student.circle_name}</small></div><div className="flexCriteriaGrid">{criteria.map((criterion:any)=>{const r=resultFor(student,criterion.id);return <button type="button" key={criterion.id} onClick={()=>setEdit({student,criterion,old:r?.record})}><span>{criterion.name} • {criterion.weight}%</span><b>{criterion.kind==='quran'?quranText(r?.record):r?.record?.completed?'تم ✓':'لم يسجل'}</b><small>{criterion.kind==='quran'?'المنجز '+(r?.done||0)+' من '+criterion.target_pages+' صفحة':'مهمة إنجاز'} • {r?.percent??0}%</small></button>})}</div>{student.student_note&&<div className="studentNotePreview"><b>ملاحظة الطالب:</b> {student.student_note}</div>}</article>})}</div>
 {edit&&<div className="recordModalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><div className="panel editPanel recordModal" role="dialog" aria-modal="true"><div className="panelHead"><div><span className="panelEyebrow">{edit.criterion.name}</span><h3>{edit.student.full_name}</h3></div><button className="secondary" onClick={()=>setEdit(null)}>إغلاق</button></div><form className="quickForm" onSubmit={save}>{edit.criterion.kind==='task'?<label className="field checkField"><input name="completed" type="checkbox" defaultChecked={!!edit.old?.completed}/><span>تم إنجاز المهمة</span></label>:<MadinahMushafRange key={(edit.old?.id||edit.student.id)+edit.criterion.id} initial={edit.old||{}}/>}<button className="primary" disabled={busy}>حفظ</button></form></div></div>}</section>
}

export function StudentFlexibleCriteria({data,onRefresh}:{data:any;onRefresh:()=>Promise<void>}){
 const [edit,setEdit]=useState<any>(null),[noteOpen,setNoteOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const today=String(data?.today||''),row=(data?.monthly||[]).find((x:any)=>String(x.record_date).slice(0,10)===today),criteria=customCriteria(data?.criteria||[]);
 if(!row)return null;
 async function save(e:any){e.preventDefault();if(!edit)return;setBusy(true);setMessage('');const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.criterion_id=edit.criterion.id;if(edit.criterion.kind==='task')body.completed=body.completed==='on';try{if(!navigator.onLine){queueOfflineOperation('criterion',body);setEdit(null);setMessage('تم الحفظ على الجهاز — بانتظار المزامنة.');return}try{await apiPost('/api/ops?action=criterion-record',body);setEdit(null);await onRefresh();setMessage('تم الحفظ.')}catch(x){if(!isNetworkFailure(x))throw x;queueOfflineOperation('criterion',body);setEdit(null);setMessage('تم الحفظ على الجهاز — ستتم المزامنة عند عودة الإنترنت.')}}catch(x){setMessage(x instanceof Error?x.message:'تعذر الحفظ')}finally{setBusy(false)}}
 async function saveNote(e:any){e.preventDefault();setBusy(true);setMessage('');const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(!navigator.onLine){queueOfflineOperation('note',body);setNoteOpen(false);setMessage('تم حفظ الملاحظة على الجهاز — بانتظار المزامنة.');return}try{await apiPost('/api/ops?action=student-note',body);setNoteOpen(false);await onRefresh();setMessage('تم حفظ الملاحظة.')}catch(x){if(!isNetworkFailure(x))throw x;queueOfflineOperation('note',body);setNoteOpen(false);setMessage('تم حفظ الملاحظة على الجهاز — ستتم المزامنة عند عودة الإنترنت.')}}catch(x){setMessage(x instanceof Error?x.message:'تعذر حفظ الملاحظة')}finally{setBusy(false)}}
 return <section className="flexCriteriaToday studentFlexCriteria"><div className="panelHead"><div><span className="panelEyebrow">سجل اليوم</span><h3>المعايير الإضافية والملاحظة</h3></div><small>{pendingOfflineCount()>0?pendingOfflineCount()+' بانتظار المزامنة':'محفوظ ومزامن'}</small></div>{message&&<div className="notice">{message}</div>}<div className="flexCriteriaGrid">{criteria.map((criterion:any)=>{const r=resultFor(row,criterion.id);return <button type="button" key={criterion.id} disabled={!!(row.approved||row.week_locked)} onClick={()=>setEdit({criterion,old:r?.record})}><span>{criterion.name} • {criterion.weight}%</span><b>{criterion.kind==='quran'?quranText(r?.record):r?.record?.completed?'تم ✓':'لم يسجل'}</b><small>{criterion.kind==='quran'?'المطلوب '+criterion.target_pages+' ص • المنجز '+(r?.done||0)+' ص':'مهمة إنجاز'} • {r?.percent??0}%</small></button>})}<button type="button" className="studentNoteButton" disabled={!!(row.approved||row.week_locked)} onClick={()=>setNoteOpen(true)}><span>ملاحظتي للمعلم</span><b>{row.student_note||'إضافة ملاحظة ＋'}</b><small>لا تدخل في الدرجة</small></button></div>
 {edit&&<div className="recordModalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><div className="panel editPanel recordModal"><div className="panelHead"><div><span className="panelEyebrow">{edit.criterion.name}</span><h3>{today}</h3></div><button className="secondary" onClick={()=>setEdit(null)}>إغلاق</button></div><form className="quickForm" onSubmit={save}>{edit.criterion.kind==='task'?<label className="field checkField"><input name="completed" type="checkbox" defaultChecked={!!edit.old?.completed}/><span>تم إنجاز المهمة</span></label>:<MadinahMushafRange key={(edit.old?.id||today)+edit.criterion.id} initial={edit.old||{}}/>}<button className="primary" disabled={busy}>حفظ</button></form></div></div>}
 {noteOpen&&<div className="recordModalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setNoteOpen(false)}}><div className="panel editPanel recordModal"><div className="panelHead"><div><span className="panelEyebrow">ملاحظتي للمعلم</span><h3>{today}</h3></div><button className="secondary" onClick={()=>setNoteOpen(false)}>إغلاق</button></div><form className="quickForm" onSubmit={saveNote}><label className="field"><span>الملاحظة</span><textarea name="note" rows={4} maxLength={1000} required defaultValue={row.student_note||''}/></label><small>هذه الملاحظة لا تدخل في التقييم.</small><button className="primary" disabled={busy}>حفظ الملاحظة</button></form></div></div>}</section>
}
