import {useEffect,useState,type FormEvent} from 'react';
import {apiGet,apiPost,apiPut,CenterRow,CircleRow,StudentRow} from './lib/api';
import {madinahSurahName} from './MadinahMushafRange';

const makkahToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const monthDays=(month:string)=>{const [y,m]=month.split('-').map(Number),last=new Date(Date.UTC(y,m,0)).getUTCDate(),out:{date:string;day:string}[]=[];for(let d=1;d<=last;d++){const dt=new Date(Date.UTC(y,m-1,d));if(dt.getUTCDay()===5)continue;out.push({date:dt.toISOString().slice(0,10),day:new Intl.DateTimeFormat('ar-SA',{weekday:'long',timeZone:'UTC'}).format(dt)})}return out};
const fmtPoints=(v:any)=>{const n=Number(v||0);return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')};

type Mode='selfService'|'motivation'|'competitions'|'notifications'|'reports'|'operations'|'joinRequests';
export default function ExtendedOperations({mode,currentRole,students,circles,centers}:{mode:Mode;currentRole:string;students:StudentRow[];circles:CircleRow[];centers:CenterRow[]}){
  const isStaff=['system_admin','center_manager','supervisor','teacher'].includes(currentRole);
  const isManager=['system_admin','center_manager','supervisor'].includes(currentRole);
  const [busy,setBusy]=useState(false),[error,setError]=useState('');const [data,setData]=useState<any>(null);
  const [month,setMonth]=useState(makkahToday().slice(0,7)),[circleId,setCircleId]=useState(''),[taskEdit,setTaskEdit]=useState<any>(null);
  const [range,setRange]=useState({from:new Date(Date.now()-6*86400000).toISOString().slice(0,10),to:new Date().toISOString().slice(0,10)});
  async function load(){setBusy(true);setError('');try{
    if(mode==='selfService')setData(await apiGet('/api/ops?action=self-service'));
    if(mode==='motivation')setData(await apiGet(`/api/ops?action=motivation&sub=list&month=${month}${circleId?`&circle_id=${circleId}`:''}`));
    if(mode==='competitions')setData(await apiGet('/api/ops?action=competitions'));
    if(mode==='notifications')setData(await apiGet('/api/ops?action=notifications'));
    if(mode==='reports')setData(await apiGet(`/api/ops?action=management-report&from=${range.from}&to=${range.to}`));
    if(mode==='operations')setData(await apiGet('/api/ops?action=admin-operations&sub=dashboard'));
    if(mode==='joinRequests')setData(await apiGet('/api/ops?action=join-requests&sub=list'));
  }catch(e){setError(e instanceof Error?e.message:'تعذر تحميل البيانات')}finally{setBusy(false)}}
  useEffect(()=>{load()},[mode]);
  async function post(path:string,body:any,reload=true){setError('');try{setBusy(true);await apiPost(path,body);if(reload)await load()}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ العملية')}finally{setBusy(false)}}
  async function put(path:string,body:any,reload=true){setError('');try{setBusy(true);await apiPut(path,body);if(reload)await load()}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ العملية')}finally{setBusy(false)}}
  const formBody=(e:FormEvent<HTMLFormElement>)=>Object.fromEntries(new FormData(e.currentTarget).entries());
  function exportReport(){
    const rows=data?.circles||[];if(!rows.length)return;
    const head=['المركز','الحلقة','المعلم','الطلاب','الحضور %','القرآن %'];
    const csv=[head,...rows.map((r:any)=>[r.center_name,r.name,r.teacher_name,r.students,r.attendance_rate,r.quran_average])]
      .map((row:any[])=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');
    const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});
    const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='center-report.csv';a.click();URL.revokeObjectURL(url);
  }
  if(busy&&!data)return <div className="emptyState">جارٍ تحميل البيانات...</div>;
  const motivationTasks=(data?.tasks||[]) as any[],activeMotivationTasks=motivationTasks.filter((t:any)=>t.is_active!==false);
  const motivationDays=monthDays(month),todayMakkah=makkahToday(),studentId=data?.student?.id;
  const entryMap=new Map<string,any>((data?.entries||[]).map((e:any)=>[String(e.student_id)+'|'+String(e.task_id)+'|'+String(e.entry_date).slice(0,10),e]));
  const studentEntry=(taskId:string,date:string)=>entryMap.get(String(studentId)+'|'+taskId+'|'+date);
  const dailyTaskPoints=(task:any,units:number)=>Math.round((Number(units||0)/Math.max(1,Number(task.max_units||1)))*Number(task.max_points||0)*100)/100;
  return <div className="extendedOps">{error&&<div className="notice">{error}</div>}
    {mode==='joinRequests'&&<><h3>طلبات الانضمام للحلقات</h3><div className="requestList">{(data?.items||[]).map((r:any)=><article key={r.id}><div><b>{r.applicant_name}</b><span>{r.circle_name} • {r.center_name}</span><small>{r.email||'—'}</small></div><div><button className="primary" onClick={()=>post('/api/ops?action=join-requests&sub=decide',{request_id:r.id,decision:'approved'})}>قبول</button><button className="secondary" onClick={()=>post('/api/ops?action=join-requests&sub=decide',{request_id:r.id,decision:'rejected'})}>رفض</button></div></article>)}</div></>}
    {mode==='selfService'&&<>{!data?.student?<div className="emptyState">لم يتم ربط الحساب بسجل طالب.</div>:<>
      <div className="studentProfileHero"><div><span>بوابة الطالب</span><h2>{data.student.full_name}</h2><p>{data.student.center_name||'—'} • {data.student.circle_name||'—'}</p></div><div className="studentPoints"><b><LiveNumber value={Number(data.student.points_balance||0)} decimals={Number(data.student.points_balance||0)%1?2:0}/></b><span>نقطة</span></div></div>
      <div className="selfPunch"><div><span>حضور اليوم</span><b>{data.attendance?.status||'لم يسجل بعد'}</b><small>{data.attendance?.check_in_at?'تم تسجيل الحضور':''}{data.attendance?.check_out_at?' • تم تسجيل الانصراف':''}</small></div><div className="selfPunchActions"><button className="primary" disabled={!!data.attendance?.check_in_at||busy} onClick={()=>post('/api/ops?action=self-service&kind=punch',{action:'check_in'})}>تسجيل الحضور</button><button className="secondary" disabled={!data.attendance?.check_in_at||!!data.attendance?.check_out_at||busy} onClick={()=>post('/api/ops?action=self-service&kind=punch',{action:'check_out'})}>تسجيل الانصراف</button></div></div>
      <div className="authSecurityNote">يمكن للطالب تسجيل الحضور والانصراف والحفظ الجديد والمراجعة لليوم الحالي فقط، ويستطيع المعلم مراجعة السجل وتعديله واعتماده.</div><h3>آخر السجلات القرآنية</h3><MiniTable rows={data.recent||[]} columns={[[ 'record_date','التاريخ'],['record_type','النوع'],['surah_no','السورة'],['from_ayah','من'],['to_ayah','إلى'],['grade','الدرجة']]}/>
    </>}</>}
    {mode==='motivation'&&<>
      <div className="opsToolbar"><label className="field"><span>الشهر</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{isStaff&&<label className="field"><span>الحلقة</span><select value={circleId} onChange={e=>setCircleId(e.target.value)}><option value="">الحلقة الافتراضية</option>{circles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<button className="secondary" onClick={load}>عرض</button></div>
      <div className="motivationHero"><div><span>رصيد التحفيز</span><b>{data?.student?<LiveNumber value={Number(data.student.points_balance||0)} decimals={Number(data.student.points_balance||0)%1?2:0}/>: '—'}</b><small>{data?.circle?.name||'الحلقة'}</small></div><div><span>المهام النشطة</span><b><LiveNumber value={activeMotivationTasks.length}/></b><small>لكل حلقة إعداد مستقل</small></div><div><span>الحد اليومي</span><b><LiveNumber value={activeMotivationTasks.reduce((n:number,t:any)=>n+Number(t.max_points||0),0)} decimals={2}/></b><small>نقطة وفق المهام الحالية</small></div></div>
      {currentRole==='student'&&<><div className="studentMonthlyHead"><div><span>مهامي اليومية</span><h3>سجل الشهر — الجمعة مستبعدة</h3></div><small>يمكن التسجيل في اليوم الحالي فقط، والنقاط تُحسب تلقائيًا.</small></div><div className="table-wrap motivationMonthlyTable"><table><thead><tr><th>اليوم</th><th>التاريخ</th>{motivationTasks.map((t:any)=><th key={t.id}>{t.name}<small>{t.answer_type==='done'?'تم = '+fmtPoints(t.max_points)+' نقطة':'من 1 إلى '+t.max_units+' • الحد '+fmtPoints(t.max_points)}</small></th>)}<th>نقاط اليوم</th></tr></thead><tbody>{motivationDays.map(d=>{const dayEntries=motivationTasks.map((t:any)=>studentEntry(t.id,d.date)),dayPoints=dayEntries.reduce((n:number,e:any)=>n+Number(e?.points||0),0),editable=d.date===todayMakkah;return <tr key={d.date} className={editable?'todayRow':''}><td>{d.day}</td><td>{d.date}</td>{motivationTasks.map((t:any)=>{const entry=studentEntry(t.id,d.date),units=Number(entry?.units||0),can=editable&&t.is_active!==false;return <td key={t.id}>{t.answer_type==='done'?<button className={'taskDoneButton '+(units>0?'done':'')} disabled={!can||busy} onClick={()=>post('/api/ops?action=motivation&sub=entry',{task_id:t.id,units:units>0?0:1,entry_date:d.date})}>{units>0?'تم ✓':editable?'تسجيل تم':'—'}</button>:can?<select className="taskCountSelect" value={units} disabled={busy} onChange={e=>post('/api/ops?action=motivation&sub=entry',{task_id:t.id,units:Number(e.target.value),entry_date:d.date})}><option value={0}>—</option>{Array.from({length:Number(t.max_units||1)},(_,i)=><option value={i+1} key={i+1}>{i+1}</option>)}</select>:<span>{units?units+'/'+t.max_units:'—'}</span>}<small className="taskCellPoints">{units?fmtPoints(entry?.points??dailyTaskPoints(t,units))+' ن':'—'}</small></td>})}<td><b>{fmtPoints(dayPoints)}</b></td></tr>})}</tbody></table></div></>}
      {isStaff&&<><div className="studentMonthlyHead"><div><span>إعداد مهام الحلقة</span><h3>{data?.circle?.name||'اختر الحلقة'}</h3></div><small>يمكن للمعلم تعديل مهام حلقته ونقاطها وإضافة مهام جديدة أو حذفها.</small></div>
        <form key={taskEdit?.id||'new-task'} className="quickForm taskConfigForm" onSubmit={async e=>{e.preventDefault();const b:any=formBody(e);b.circle_id=circleId||data?.circle?.id;if(taskEdit){b.task_id=taskEdit.id;await put('/api/ops?action=motivation&sub=task-edit',b)}else await post('/api/ops?action=motivation&sub=task',b);setTaskEdit(null);e.currentTarget.reset()}}>
          <label className="field"><span>اسم المهمة</span><input name="name" defaultValue={taskEdit?.name||''} required/></label>
          <label className="field"><span>نوع الإجابة</span><select name="answer_type" defaultValue={taskEdit?.answer_type||'done'}><option value="done">تم / لم يتم</option><option value="count">عدد من 1 إلى حد أعلى</option></select></label>
          <label className="field"><span>الحد الأعلى للإجابة</span><input name="max_units" type="number" min="1" max="100" defaultValue={taskEdit?.max_units||1}/></label>
          <label className="field"><span>أقصى نقاط للمهمة</span><input name="max_points" type="number" min="0.01" step="0.01" defaultValue={taskEdit?.max_points||1} required/></label>
          <label className="field"><span>الترتيب</span><input name="sort_order" type="number" min="0" defaultValue={taskEdit?.sort_order||0}/></label>
          <button className="primary">{taskEdit?'حفظ تعديل المهمة':'إضافة المهمة'}</button>{taskEdit&&<button className="secondary" type="button" onClick={()=>setTaskEdit(null)}>إلغاء التعديل</button>}
        </form>
        <div className="taskConfigGrid">{activeMotivationTasks.map((t:any)=><article key={t.id}><div><b>{t.name}</b><small>{t.answer_type==='done'?'تم/لم يتم':'1–'+t.max_units} • الحد {fmtPoints(t.max_points)} نقطة</small></div><div><button className="secondary" onClick={()=>setTaskEdit(t)}>تعديل</button><button className="dangerButton" onClick={()=>{if(window.confirm('حذف هذه المهمة من المهام النشطة؟'))post('/api/ops?action=motivation&sub=task-delete',{task_id:t.id})}}>حذف</button></div></article>)}</div>
        {activeMotivationTasks.length>0&&<form className="quickForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=motivation&sub=entry',formBody(e));e.currentTarget.reset()}}><h3>تسجيل إنجاز عن طالب</h3><label className="field"><span>الطالب</span><select name="student_id" required><option value="">اختر</option>{(data.students||[]).map((s:any)=><option value={s.id} key={s.id}>{s.full_name}</option>)}</select></label><label className="field"><span>المهمة</span><select name="task_id" required><option value="">اختر</option>{activeMotivationTasks.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label className="field"><span>الإجابة/العدد</span><input name="units" type="number" min="0" defaultValue="1"/></label><label className="field"><span>التاريخ</span><input name="entry_date" type="date" defaultValue={todayMakkah}/></label><button className="primary">حفظ الإنجاز</button></form>}
      </>}
      <h3 className="profileSubhead">الجوائز</h3>
      {isStaff&&<form className="quickForm" onSubmit={async e=>{e.preventDefault();const b:any=formBody(e);b.circle_id=circleId||data?.circle?.id;await post('/api/ops?action=motivation&sub=reward',b);e.currentTarget.reset()}}><label className="field"><span>اسم الجائزة</span><input name="name" required/></label><label className="field"><span>تكلفة النقاط</span><input name="points_cost" type="number" min="1" required/></label><label className="field"><span>الكمية</span><input name="stock" type="number" min="0" required/></label><label className="field"><span>رابط الصورة</span><input name="image_path"/></label><label className="field"><span>وصف</span><input name="description"/></label><button className="primary">إضافة جائزة</button></form>}
      <div className="rewardGrid">{(data?.rewards||[]).map((r:any)=><article key={r.id}><span>جائزة</span><h3>{r.name}</h3><b>{r.points_cost} نقطة</b><small>المتاح: {r.stock}</small>{currentRole==='student'&&<button className="primary" disabled={r.stock<1} onClick={()=>post('/api/ops?action=motivation&sub=reward-request',{reward_id:r.id})}>طلب الجائزة</button>}</article>)}</div>
      <h3 className="profileSubhead">الثلاثة الأوائل في الحلقة</h3><MiniTable rows={data?.top3||[]} columns={[[ 'full_name','الطالب'],['points_balance','النقاط'],['quran_average','متوسط القرآن'],['attendance_rate','الحضور %']]}/><h3 className="profileSubhead">العشرة الأوائل في المركز</h3><MiniTable rows={data?.centerTop10||[]} columns={[[ 'full_name','الطالب'],['circle_name','الحلقة'],['points_balance','النقاط']]}/><h3 className="profileSubhead">الأكثر تحسنًا في الحلقة</h3><MiniTable rows={data?.mostImproved||[]} columns={[[ 'full_name','الطالب'],['previous_avg','المتوسط السابق'],['current_avg','المتوسط الحالي']]}/><h3 className="profileSubhead">الأكثر تحسنًا في المركز</h3><MiniTable rows={data?.centerMostImproved||[]} columns={[[ 'full_name','الطالب'],['circle_name','الحلقة'],['previous_avg','المتوسط السابق'],['current_avg','المتوسط الحالي']]}/>
      {isStaff&&<><h3 className="profileSubhead">طلبات الجوائز</h3><div className="requestList">{(data?.requests||[]).map((r:any)=><article key={r.id}><div><b>{r.full_name}</b><span>{r.reward_name}</span><small>{r.status}</small></div>{r.status==='pending'&&<button className="primary" onClick={()=>post('/api/ops?action=motivation&sub=reward-approve',{request_id:r.id})}>اعتماد</button>}{r.status==='approved'&&<button className="primary" onClick={()=>post('/api/ops?action=motivation&sub=reward-deliver',{request_id:r.id})}>تم التسليم وخصم النقاط</button>}</article>)}</div></>}
    </>}
    {mode==='competitions'&&<>
      <div className="studentMonthlyHead"><div><span>سجل عام للمركز</span><h3>المسابقات والنتائج</h3></div><small>سجل مستقل يشمل طلاب المركز، مع بقاء كل طالب منسوبًا إلى حلقته.</small></div>
      {isManager&&<form className="quickForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=competitions&sub=create',formBody(e));e.currentTarget.reset()}}><label className="field"><span>اسم المسابقة</span><input name="title" required/></label>{currentRole==='system_admin'&&<label className="field"><span>المركز</span><select name="center_id" required><option value="">اختر المركز</option>{centers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>}<label className="field"><span>النقاط القصوى</span><input name="max_points" type="number" min="1" defaultValue="100" required/></label><label className="field"><span>البداية</span><input name="start_date" type="date" required/></label><label className="field"><span>النهاية</span><input name="end_date" type="date" required/></label><button className="primary">إضافة إلى سجل المسابقات</button></form>}
      <div className="competitionGrid">{(data||[]).map((c:any)=><article key={c.id}><div><span>مسابقة المركز</span><h3>{c.title}</h3><small>{c.center_name||'المركز'} • {String(c.start_date).slice(0,10)} — {String(c.end_date).slice(0,10)} • {c.max_points||100} نقطة</small></div>{isManager&&<button className="secondary" onClick={async()=>{const title=prompt('اسم المسابقة',c.title);if(!title)return;const points=prompt('النقاط القصوى',String(c.max_points||100));await put('/api/ops?action=competitions&sub=edit',{id:c.id,title,max_points:Number(points||c.max_points||100)})}}>تعديل</button>}{(c.entries||[]).length>0&&<div className="competitionLeaders">{c.entries.map((e:any,i:number)=><p key={e.student_id}><b>{i+1}</b>{e.full_name}<small>{e.student_circle||'—'}</small><span>{e.score}</span></p>)}</div>}</article>)}</div>
      {isStaff&&(data||[]).length>0&&<form className="quickForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=competitions&sub=score',formBody(e));e.currentTarget.reset()}}><label className="field"><span>المسابقة</span><select name="competition_id" required><option value="">اختر</option>{data.map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="field"><span>الطالب</span><select name="student_id" required><option value="">اختر</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label className="field"><span>الدرجة</span><input name="score" type="number" min="0" max="10000" required/></label><label className="field"><span>ملاحظة</span><input name="notes"/></label><button className="primary">حفظ النتيجة</button></form>}
    </>}
    {mode==='notifications'&&<>
      {currentRole==='teacher'&&<form className="quickForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=notifications&sub=student-message',formBody(e));e.currentTarget.reset()}}><label className="field"><span>الطالب</span><select name="student_id" required><option value="">اختر الطالب</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label className="field"><span>العنوان</span><input name="title" defaultValue="رسالة من المعلم"/></label><label className="field"><span>الرسالة</span><input name="body" required/></label><button className="primary">حفظ وإرسال داخل المنصة</button><small>إرسال الرسالة إلى رقم الجوال محفوظ ومجهز، لكنه غير مفعل حاليًا.</small></form>}
      {isManager&&<form className="quickForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=notifications&sub=send',formBody(e));e.currentTarget.reset()}}><label className="field"><span>العنوان</span><input name="title" required/></label><label className="field"><span>الرسالة</span><input name="body" required/></label>{currentRole==='system_admin'&&<label className="field"><span>المركز</span><select name="center_id"><option value="">جميع المستخدمين</option>{centers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>}<button className="primary">إرسال الإشعار</button></form>}
      <div className="notificationList">{(data||[]).map((n:any)=><article key={n.id} className={n.is_read?'read':''}><div><span>{n.kind}</span><h3>{n.title}</h3><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('ar-SA')}</small></div>{!n.is_read&&<button className="secondary" onClick={()=>put(`/api/ops?action=notifications&sub=read&id=${n.id}`,{})}>تمت القراءة</button>}</article>)}</div>
    </>}
    {mode==='reports'&&<><div className="opsToolbar"><label className="field"><span>من</span><input type="date" value={range.from} onChange={e=>setRange(x=>({...x,from:e.target.value}))}/></label><label className="field"><span>إلى</span><input type="date" value={range.to} onChange={e=>setRange(x=>({...x,to:e.target.value}))}/></label><button className="primary" onClick={load}>تحديث التقرير</button><button className="secondary" onClick={()=>window.print()}>طباعة / حفظ PDF</button><button className="secondary" onClick={exportReport}>Excel / CSV</button><button className="secondary" onClick={()=>{const d=new Date();setRange({from:new Date(d.getTime()-6*86400000).toISOString().slice(0,10),to:d.toISOString().slice(0,10)})}}>أسبوعي</button><button className="secondary" onClick={()=>{const d=new Date();setRange({from:new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10),to:d.toISOString().slice(0,10)})}}>شهري</button><button className="secondary" onClick={()=>{const d=new Date();setRange({from:new Date(d.getFullYear(),d.getMonth()-2,1).toISOString().slice(0,10),to:d.toISOString().slice(0,10)})}}>ربع سنوي</button><button className="secondary" onClick={()=>{const d=new Date();setRange({from:new Date(d.getFullYear(),d.getMonth()-5,1).toISOString().slice(0,10),to:d.toISOString().slice(0,10)})}}>نصف سنوي</button><button className="secondary" onClick={()=>{const d=new Date();setRange({from:new Date(d.getFullYear(),0,1).toISOString().slice(0,10),to:d.toISOString().slice(0,10)})}}>سنوي</button></div><h3>أداء الحلقات</h3><MiniTable rows={data?.circles||[]} columns={[[ 'center_name','المركز'],['name','الحلقة'],['teacher_name','المعلم'],['students','الطلاب'],['attendance_rate','الحضور %'],['quran_average','القرآن %']]}/><h3 className="profileSubhead">طلاب يحتاجون متابعة</h3><MiniTable rows={data?.needs_followup||[]} columns={[[ 'full_name','الطالب'],['circle_name','الحلقة'],['attendance_rate','الحضور %'],['quran_average','القرآن %']]}/></>}
    {mode==='operations'&&<><div className={`readinessBanner ${data?.ready?'ready':''}`}><div><span>جاهزية التشغيل</span><h2>{data?.ready?'المنصة جاهزة تشغيليًا':'توجد عناصر تحتاج استكمالًا'}</h2></div><b>{(data?.checks||[]).filter((x:any)=>x.ok).length}/{data?.checks?.length||0}</b></div><div className="readinessGrid">{(data?.checks||[]).map((x:any)=><article className={x.ok?'ok':''} key={x.label}><b>{x.ok?'✓':'!'}</b><span>{x.label}</span></article>)}</div>
      {data?.settings&&<form className="quickForm" onSubmit={async e=>{e.preventDefault();await put('/api/ops?action=admin-operations&sub=settings',formBody(e))}}><label className="field"><span>سماح التأخر</span><input name="grace_minutes" type="number" defaultValue={data.settings.grace_minutes}/></label><label className="field"><span>خصم التأخر البسيط</span><input name="minor_late_penalty" type="number" defaultValue={data.settings.minor_late_penalty}/></label><label className="field"><span>خصم التأخر الكبير</span><input name="major_late_penalty" type="number" defaultValue={data.settings.major_late_penalty}/></label><label className="field"><span>وزن الحفظ</span><input name="memorization_weight" type="number" defaultValue={data.settings.memorization_weight}/></label><label className="field"><span>وزن المراجعة</span><input name="review_weight" type="number" defaultValue={data.settings.review_weight}/></label><label className="field"><span>وزن الانضباط</span><input name="discipline_weight" type="number" defaultValue={data.settings.discipline_weight}/></label><label className="field"><span>مهلة التعديل بالأيام</span><input name="edit_window_days" type="number" defaultValue={data.settings.edit_window_days}/></label><button className="primary">حفظ الإعدادات</button></form>}
      <div className="opsFormsGrid"><form className="miniOpsForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=admin-operations&sub=weekly-lock',formBody(e));e.currentTarget.reset()}}><h3>القفل الأسبوعي النهائي</h3><select name="circle_id" required><option value="">اختر الحلقة</option>{circles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input name="week_start" type="date" required/><select name="locked" defaultValue="true"><option value="true">إقفال الأسبوع</option><option value="false">فتح الأسبوع</option></select><button className="primary">تنفيذ</button></form><form className="miniOpsForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=admin-operations&sub=holiday',formBody(e));e.currentTarget.reset()}}><h3>إضافة إجازة</h3><input name="holiday_date" type="date" required/><input name="title" placeholder="اسم الإجازة" required/><select name="kind"><option value="official">رسمية</option><option value="special">خاصة</option></select>{currentRole==='system_admin'&&<select name="center_id"><option value="">عامة</option>{centers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select>}<button className="primary">إضافة</button></form><form className="miniOpsForm" onSubmit={async e=>{e.preventDefault();await post('/api/ops?action=admin-operations&sub=edit-exception',formBody(e));e.currentTarget.reset()}}><h3>فتح تعديل استثنائي</h3><select name="student_id" required><option value="">اختر الطالب</option>{students.map(s=><option value={s.id} key={s.id}>{s.full_name}</option>)}</select><input name="record_date" type="date" required/><input name="reason" placeholder="سبب فتح التعديل" required/><button className="primary">اعتماد</button></form></div><h3 className="profileSubhead">الأسابيع المقفلة</h3><MiniTable rows={data?.weekly_locks||[]} columns={[[ 'week_start','بداية الأسبوع'],['circle_name','الحلقة'],['locked_at','وقت القفل']]}/><h3 className="profileSubhead">الإجازات</h3><MiniTable rows={data?.holidays||[]} columns={[[ 'holiday_date','التاريخ'],['title','الإجازة'],['kind','النوع']]}/><h3 className="profileSubhead">سجل العمليات</h3><MiniTable rows={data?.audit||[]} columns={[[ 'created_at','الوقت'],['actor_name','المستخدم'],['action','العملية'],['entity_type','العنصر'],['reason','السبب']]}/></>}
  </div>
}
function MiniTable({rows,columns}:{rows:any[];columns:[string,string][]}){if(!rows?.length)return <div className="empty">لا توجد بيانات.</div>;const show=(r:any,k:string)=>k==='surah_no'&&r[k]!=null?madinahSurahName(Number(r[k])):r[k]===null||r[k]===undefined?'—':String(r[k]).slice(0,80);return <div className="table-wrap"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={r.id||i}>{columns.map(([k])=><td key={k}>{show(r,k)}</td>)}</tr>)}</tbody></table></div>}
