import {useState} from 'react';
import {apiPost,apiPut} from './lib/api';
import {MadinahMushafRange,madinahSurahName} from './MadinahMushafRange';
const stamp=(date:string,time:string)=>time?date+'T'+time+':00+03:00':'',timeValue=(v:any)=>v?new Date(v).toLocaleTimeString('en-GB',{timeZone:'Asia/Riyadh',hour:'2-digit',minute:'2-digit',hour12:false}):'';
export default function TeacherDailyTable({data,date,onRefresh,onProfile}:{data:any;date:string;onRefresh:()=>Promise<void>;onProfile:(id:string)=>void}){
 const [edit,setEdit]=useState<any>(null),[attendanceEdit,setAttendanceEdit]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const rows=data?.students||[],approvals=data?.approvals||[],isLocked=(r:any)=>approvals.some((a:any)=>a.circle_id===r.circle_id);
 async function saveAttendance(e:any){e.preventDefault();if(!attendanceEdit||isLocked(attendanceEdit.r))return;const f:any=Object.fromEntries(new FormData(e.currentTarget).entries()),status=String(f.status||''),inTime=String(f.check_in_time||''),outTime=String(f.check_out_time||'');if(['present','late'].includes(status)&&!inTime){setError('أدخل وقت الحضور.');return}setBusy(true);setError('');try{await apiPost('/api/attendance',{student_id:attendanceEdit.r.id,attendance_date:date,status,check_in_at:['present','late'].includes(status)?stamp(date,inTime):'',check_out_at:['present','late'].includes(status)&&outTime?stamp(date,outTime):''});setAttendanceEdit(null);await onRefresh()}catch(x){setError(x instanceof Error?x.message:'تعذر تعديل الحضور')}finally{setBusy(false)}}
 async function qsave(e:any){e.preventDefault();if(!edit||isLocked(edit.r))return;setBusy(true);setError('');try{const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.student_id=edit.r.id;body.record_date=date;body.record_type=edit.kind;if(edit.old?.id){body.id=edit.old.id;await apiPut('/api/memorization',body)}else await apiPost('/api/memorization',body);setEdit(null);await onRefresh()}catch(x){setError(x instanceof Error?x.message:'تعذر حفظ السجل')}finally{setBusy(false)}}
 const fmt=(v:any)=>v?new Date(v).toLocaleTimeString('ar-SA',{timeZone:'Asia/Riyadh',hour:'2-digit',minute:'2-digit'}):'—',qr=(x:any)=>x?(madinahSurahName(Number(x.surah_no||1))+' ص'+(x.from_page||'—')+' ← '+madinahSurahName(Number(x.to_surah_no||x.surah_no||1))+' ص'+(x.to_page||'—')):'لم يسجل';
 return <>{error&&<div className="notice">{error}</div>}<div className="table-wrap teacherDailyUnified"><table><thead><tr><th>الطالب</th><th>التاريخ</th><th>الحضور</th><th>وقت الحضور</th><th>وقت الانصراف</th><th>التأخير</th><th>المراجعة</th><th>الحفظ الجديد</th><th>الصفحات</th><th>التقييم</th><th>ملاحظة</th></tr></thead><tbody>{rows.map((r:any)=>{const locked=isLocked(r),pages=Number(r.review_record?.page_count||0)+Number(r.new_record?.page_count||0);return <tr key={r.id}><td><button className="tableAction" onClick={()=>onProfile(r.id)}>{r.full_name}</button><small>{r.circle_name}</small></td><td>{date}</td><td><button className="tableAction" disabled={locked} onClick={()=>setAttendanceEdit({r})}>{r.attendance_status==='present'?'حاضر':r.attendance_status==='late'?'متأخر':r.attendance_status==='absent'?'غائب':r.attendance_status==='excused'?'مستأذن':'لم يسجل'} {locked?'✓':'✎'}</button></td><td>{fmt(r.check_in_at)}</td><td>{fmt(r.check_out_at)}</td><td>{r.late_minutes?String(r.late_minutes)+' د':'—'}</td><td><button disabled={locked} className="tableAction" onClick={()=>!locked&&setEdit({r,kind:'review',old:r.review_record})}>{qr(r.review_record)} {r.review_record?'✎':'＋'}</button><small>{r.review_score??0}/40</small></td><td><button disabled={locked} className="tableAction" onClick={()=>!locked&&setEdit({r,kind:'new',old:r.new_record})}>{qr(r.new_record)} {r.new_record?'✎':'＋'}</button><small>{r.new_score??0}/30</small></td><td>{pages||'—'}</td><td>{r.daily_score===null?'مستبعد':(r.daily_score??0)+'/100'}<small>{r.attendance_score===null?'':(r.attendance_score??0)+'/30 حضور'}</small></td><td><small>{r.goals||'—'}</small><button className="secondary" onClick={()=>onProfile(r.id)}>ملف الطالب</button></td></tr>})}</tbody></table></div>
 {attendanceEdit&&<div className="panel editPanel"><div className="panelHead"><div><span className="panelEyebrow">تعديل الحضور والانصراف</span><h3>{attendanceEdit.r.full_name} — {date}</h3></div><button className="secondary" onClick={()=>setAttendanceEdit(null)}>إغلاق</button></div><form className="quickForm" onSubmit={saveAttendance}><label className="field"><span>الحالة</span><select name="status" defaultValue={attendanceEdit.r.attendance_status||'present'}><option value="present">حاضر</option><option value="late">متأخر</option><option value="absent">غائب</option><option value="excused">مستأذن</option></select></label><label className="field"><span>وقت الحضور</span><input name="check_in_time" type="time" defaultValue={timeValue(attendanceEdit.r.check_in_at)}/></label><label className="field"><span>وقت الانصراف</span><input name="check_out_time" type="time" defaultValue={timeValue(attendanceEdit.r.check_out_at)}/></label><button className="primary" disabled={busy}>حفظ التعديل</button></form></div>}
 {edit&&<div className="panel editPanel"><div className="panelHead"><div><span className="panelEyebrow">{edit.kind==='review'?'المراجعة':'الحفظ الجديد'}</span><h3>{edit.r.full_name}</h3></div><button className="secondary" onClick={()=>setEdit(null)}>إغلاق</button></div><form className="quickForm" onSubmit={qsave}><MadinahMushafRange key={(edit.old?.id||edit.r.id)+edit.kind} initial={edit.old||{}}/><label className="field"><span>ملاحظات</span><input name="notes"/></label><button className="primary" disabled={busy}>{edit.old?'حفظ التعديل':'حفظ السجل'}</button></form></div>}</>
}