import {useState} from 'react';
import {apiPost,apiPut} from './lib/api';
import {MadinahMushafRange} from './MadinahMushafRange';
export default function TeacherDailyTable({data,date,onRefresh,onProfile}:{data:any;date:string;onRefresh:()=>Promise<void>;onProfile:(id:string)=>void}){
 const [edit,setEdit]=useState<any>(null); const rows=data?.students||[];
 async function attendance(r:any,status:string){await apiPost('/api/attendance',{student_id:r.id,attendance_date:date,status,late_minutes:r.late_minutes||0,check_in_at:(status==='present'||status==='late')&&!r.check_in_at?new Date().toISOString():r.check_in_at||'',check_out_at:r.check_out_at||''});await onRefresh()}
 async function checkout(r:any){await apiPost('/api/attendance',{student_id:r.id,attendance_date:date,status:r.attendance_status||'present',late_minutes:r.late_minutes||0,check_in_at:r.check_in_at||'',check_out_at:new Date().toISOString()});await onRefresh()}
 async function qsave(e:any){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.student_id=edit.r.id;body.record_date=date;body.record_type=edit.kind;if(edit.old?.id){body.id=edit.old.id;await apiPut('/api/memorization',body)}else await apiPost('/api/memorization',body);setEdit(null);await onRefresh()}
 const fmt=(v:any)=>v?new Date(v).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'}):'—';
 const qr=(x:any)=>x?('ص '+(x.from_page||'—')+'–'+(x.to_page||'—')+' • '+(x.grade??'—')+'%'):'لم يسجل';
 return <><div className="table-wrap teacherDailyUnified"><table><thead><tr><th>الطالب</th><th>الحضور</th><th>وقت الوصول</th><th>المطلوب مراجعة</th><th>المنجز مراجعة</th><th>المطلوب جديد</th><th>المنجز جديد</th><th>الدرجة</th><th>ملاحظة</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><button className="tableAction" onClick={()=>onProfile(r.id)}>{r.full_name}</button><small>{r.circle_name}</small></td><td><select value={r.attendance_status||''} onChange={e=>attendance(r,e.target.value)}><option value="">لم يسجل</option><option value="present">حاضر</option><option value="late">متأخر</option><option value="absent">غائب</option><option value="excused">مستأذن</option></select>{!r.check_out_at&&r.check_in_at&&<button className="secondary compactAction" onClick={()=>checkout(r)}>انصراف</button>}</td><td>{fmt(r.check_in_at)}{r.late_minutes?<small>تأخر {r.late_minutes} د</small>:null}</td><td>{r.review_target||'—'}</td><td><button className="tableAction" onClick={()=>setEdit({r,kind:'review',old:r.review_record})}>{qr(r.review_record)} {r.review_record?'✎':'＋'}</button><small>{r.review_score??0}/40</small></td><td>{r.new_target||'—'}</td><td><button className="tableAction" onClick={()=>setEdit({r,kind:'new',old:r.new_record})}>{qr(r.new_record)} {r.new_record?'✎':'＋'}</button><small>{r.new_score??0}/30</small></td><td>{r.daily_score===null?'مستبعد':(r.daily_score??0)+'/100'}<small>{r.attendance_score===null?'':(r.attendance_score??0)+'/30 حضور'}</small></td><td><small>{r.goals||'—'}</small><button className="secondary" onClick={()=>onProfile(r.id)}>ملف الطالب</button></td></tr>)}</tbody></table></div>
 {edit&&<div className="panel editPanel"><div className="panelHead"><div><span className="panelEyebrow">{edit.kind==='review'?'المراجعة':'الحفظ الجديد'}</span><h3>{edit.r.full_name}</h3></div><button className="secondary" onClick={()=>setEdit(null)}>إغلاق</button></div><form className="quickForm" onSubmit={qsave}><MadinahMushafRange key={(edit.old?.id||edit.r.id)+edit.kind} initial={edit.old||{}}/><label className="field"><span>الدرجة</span><input name="grade" type="number" min="0" max="100" step="0.5" defaultValue={edit.old?.grade||''}/></label><label className="field"><span>ملاحظات</span><input name="notes"/></label><button className="primary">{edit.old?'حفظ التعديل':'حفظ السجل'}</button></form></div>}</>
}
