import {useState} from 'react';
import {apiPost,apiPut} from './lib/api';
import {MadinahMushafRange,madinahSurahName} from './MadinahMushafRange';
const stamp=(date:string,time:string)=>time?date+'T'+time+':00+03:00':'',timeValue=(v:any)=>v?new Date(v).toLocaleTimeString('en-GB',{timeZone:'Asia/Riyadh',hour:'2-digit',minute:'2-digit',hour12:false}):'';
function quranText(x:any){return x?(madinahSurahName(Number(x.surah_no||1))+' ص'+(x.from_page||'—')+' ← '+madinahSurahName(Number(x.to_surah_no||x.surah_no||1))+' ص'+(x.to_page||'—')):'لم يسجل'}
function band(v:any){return v==='green'?'band-green':v==='yellow'?'band-yellow':v==='red'?'band-red':''}
export default function TeacherDailyTable({data,date,onRefresh,onProfile}:{data:any;date:string;onRefresh:()=>Promise<void>;onProfile:(id:string)=>void}){
 const [edit,setEdit]=useState<any>(null),[attendanceEdit,setAttendanceEdit]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const rows=data?.students||[],approvals=data?.approvals||[],isLocked=(r:any)=>approvals.some((a:any)=>a.circle_id===r.circle_id);
 const allCustom=new Map<string,any>();for(const list of Object.values(data?.criteria_by_circle||{}) as any[])for(const c of (list||[]))if(!c.system_key)allCustom.set(String(c.id),c);const customCriteria=[...allCustom.values()];
 async function saveAttendance(e:any){e.preventDefault();if(!attendanceEdit||isLocked(attendanceEdit.r))return;const f:any=Object.fromEntries(new FormData(e.currentTarget).entries()),status=String(f.status||''),inTime=String(f.check_in_time||''),outTime=String(f.check_out_time||'');if(['present','late'].includes(status)&&!inTime){setError('أدخل وقت الحضور.');return}setBusy(true);setError('');try{await apiPost('/api/attendance',{student_id:attendanceEdit.r.id,attendance_date:date,status,check_in_at:['present','late'].includes(status)?stamp(date,inTime):'',check_out_at:['present','late'].includes(status)&&outTime?stamp(date,outTime):''});setAttendanceEdit(null);await onRefresh()}catch(x){setError(x instanceof Error?x.message:'تعذر تعديل الحضور')}finally{setBusy(false)}}
 async function qsave(e:any){e.preventDefault();if(!edit||isLocked(edit.r))return;setBusy(true);setError('');try{const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.student_id=edit.r.id;body.record_date=date;if(edit.kind==='criterion'){body.criterion_id=edit.criterion.id;if(edit.criterion.kind==='task')body.completed=body.completed==='on';await apiPost('/api/ops?action=criterion-record',body)}else{body.record_type=edit.kind;if(edit.old?.id){body.id=edit.old.id;await apiPut('/api/memorization',body)}else await apiPost('/api/memorization',body)}setEdit(null);await onRefresh()}catch(x){setError(x instanceof Error?x.message:'تعذر حفظ السجل')}finally{setBusy(false)}}
 const fmt=(v:any)=>v?new Date(v).toLocaleTimeString('ar-SA',{timeZone:'Asia/Riyadh',hour:'2-digit',minute:'2-digit'}):'—';
 return <>{error&&<div className="notice">{error}</div>}<div className="table-wrap teacherDailyUnified"><table><thead><tr><th>الطالب</th><th>التاريخ</th><th>الحضور</th><th>وقت الحضور</th><th>وقت الانصراف</th><th>التأخير</th><th>المراجعة</th><th>الحفظ الجديد</th>{customCriteria.map((c:any)=><th key={c.id}>{c.name}<small>{c.weight}%</small></th>)}<th>التقييم الآلي</th><th>ملاحظة الطالب</th></tr></thead><tbody>{rows.map((r:any)=>{const locked=isLocked(r),results=r.criteria_results||[];return <tr key={r.id}><td><button className="tableAction" onClick={()=>onProfile(r.id)}>{r.full_name}</button><small>{r.circle_name}</small></td><td>{date}</td><td><button className="tableAction" disabled={locked} onClick={()=>setAttendanceEdit({r})}>{r.attendance_status==='present'?'حاضر':r.attendance_status==='late'?'متأخر':r.attendance_status==='absent'?'غائب':r.attendance_status==='excused'?'مستأذن':'لم يسجل'} {locked?'✓':'✎'}</button></td><td>{fmt(r.check_in_at)}</td><td>{fmt(r.check_out_at)}</td><td>{r.late_minutes?String(r.late_minutes)+' د':'—'}</td><td><button disabled={locked} className="tableAction" onClick={()=>!locked&&setEdit({r,kind:'review',old:r.review_record})}>{quranText(r.review_record)} {r.review_record?'✎':'＋'}</button><small>{results.find((x:any)=>x.system_key==='review')?.percent??'—'}%</small></td><td><button disabled={locked} className="tableAction" onClick={()=>!locked&&setEdit({r,kind:'new',old:r.new_record})}>{quranText(r.new_record)} {r.new_record?'✎':'＋'}</button><small>{results.find((x:any)=>x.system_key==='new')?.percent??'—'}%</small></td>
 {customCriteria.map((criterion:any)=>{const cr=results.find((x:any)=>String(x.id)===String(criterion.id)),belongs=(data?.criteria_by_circle?.[r.circle_id]||[]).some((x:any)=>String(x.id)===String(criterion.id));return <td key={criterion.id}>{!belongs?'—':<button disabled={locked} className="tableAction" onClick={()=>!locked&&setEdit({r,kind:'criterion',criterion,old:cr?.record})}>{criterion.kind==='quran'?quranText(cr?.record):cr?.record?.completed?'تم ✓':'لم يسجل'} {cr?.record?'✎':'＋'}<small>{cr?.percent??0}% • {criterion.weight}%</small></button>}</td>})}
 <td><strong className={'autoScore '+band(r.band)}>{r.daily_score===null?'—':(r.daily_score??0)+'/100'}</strong></td><td><small>{r.student_note||'—'}</small><button className="secondary" onClick={()=>onProfile(r.id)}>ملف الطالب</button></td></tr>})}</tbody></table></div>
 {attendanceEdit&&<div className="recordModalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setAttendanceEdit(null)}}><div className="panel editPanel recordModal" role="dialog" aria-modal="true"><div className="panelHead"><div><span className="panelEyebrow">تعديل الحضور والانصراف</span><h3>{attendanceEdit.r.full_name} — {date}</h3></div><button className="secondary" onClick={()=>setAttendanceEdit(null)}>إغلاق</button></div><form className="quickForm" onSubmit={saveAttendance}><label className="field"><span>الحالة</span><select name="status" defaultValue={attendanceEdit.r.attendance_status||'present'}><option value="present">حاضر</option><option value="late">متأخر</option><option value="absent">غائب</option><option value="excused">مستأذن</option></select></label><label className="field"><span>وقت الحضور</span><input name="check_in_time" type="time" defaultValue={timeValue(attendanceEdit.r.check_in_at)}/></label><label className="field"><span>وقت الانصراف</span><input name="check_out_time" type="time" defaultValue={timeValue(attendanceEdit.r.check_out_at)}/></label><button className="primary" disabled={busy}>حفظ التعديل</button></form></div></div>}
 {edit&&<div className="recordModalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><div className="panel editPanel recordModal" role="dialog" aria-modal="true"><div className="panelHead"><div><span className="panelEyebrow">{edit.kind==='criterion'?edit.criterion.name:edit.kind==='review'?'المراجعة':'الحفظ الجديد'}</span><h3>{edit.r.full_name}</h3></div><button className="secondary" onClick={()=>setEdit(null)}>إغلاق</button></div><form className="quickForm" onSubmit={qsave}>{edit.kind==='criterion'&&edit.criterion.kind==='task'?<label className="field checkField"><input name="completed" type="checkbox" defaultChecked={!!edit.old?.completed}/><span>تم إنجاز المهمة</span></label>:<MadinahMushafRange key={(edit.old?.id||edit.r.id)+(edit.criterion?.id||edit.kind)} initial={edit.old||{}}/>}<button className="primary" disabled={busy}>{edit.old?'حفظ التعديل':'حفظ السجل'}</button></form></div></div>}</>
}
